FAT regression test fix
Crown-Commercial-Service/ccs-scale-fat-tests pull request #2
Opened 2021-07-26 21:01 UTC by himaninare

2021-07-30 13:24 UTC, amrutha-sireesh requested changes

2021-07-30 13:24 UTC, amrutha-sireesh commented on src/test/resources/FeatureFiles/CCSLatest/ccs_fm2_technical_security.feature
> +    And  User clicks on the "Continue" button
Please use
User selects which "<areaSuits>" your requirements instead

2021-08-03 08:18 UTC, himaninare commented on src/test/resources/FeatureFiles/CCSLatest/ccs_fm2_technical_security.feature
> +    And  User clicks on the "Continue" button
Changes made

2021-08-03 08:18 UTC, himaninare commented on src/main/java/com/scale/businessPages/E2EPage.java
> +        waitForSeconds(5);
Changes made

2021-08-04 07:30 UTC, amrutha-sireesh commented on src/test/resources/FeatureFiles/CCSLatest/All_questioncontent_errorhandling.feature
Himani, Can you please apply 'area' changes to all relevant places?

2021-08-04 07:30 UTC, amrutha-sireesh commented on config/ApplicationConfig.properties
> +baseURL=https://webdev.crowncommercial.gov.uk/
Do you want this change?

2021-08-04 14:02 UTC, amrutha-sireesh approved these changes

2021-08-04 14:02 UTC, merged