add gmLite and searchAgreement tests
Crown-Commercial-Service/ccs-scale-fat-tests pull request #6
Opened 2021-08-27 07:57 UTC by Toyinccs

2021-09-13 16:45 UTC, amrutha-sireesh requested changes
Toyin, I have added few comments, no major changes identified. Thanks

2021-09-13 16:45 UTC, amrutha-sireesh commented on src/main/java/com/scale/businessPages/AgreementPage.java
> +    private String allAccordionSections = "button.govuk-accordion__open-all[aria-expanded='true']";
Can you move class variable declaration above functions?

2021-09-13 16:45 UTC, amrutha-sireesh commented on src/main/java/com/scale/framework/utility/API/APIBase.java
> +    }
Can you please format code?

2021-09-13 16:45 UTC, amrutha-sireesh commented on src/main/java/com/scale/framework/utility/API/APIBase.java
> +            }
no need for this for loop here, right?

2021-09-13 16:45 UTC, amrutha-sireesh commented on src/main/java/com/scale/framework/utility/API/APIBase.java
> +        log.info(size);
Can you please add relevant info if you are using log statements

2021-09-13 16:45 UTC, amrutha-sireesh commented on src/main/java/com/scale/businessPages/AgreementPage.java
> +    private Logger log = Log.getLogger(ContactCCSPage.class);
class name here is AgreementPage. I can see some class logger holds wrong class name across the repo :(

2021-09-13 16:45 UTC, amrutha-sireesh commented on src/main/java/com/scale/businessPages/HomePage.java
> +        String XPATH = "//*[@id= '"+ elementName +"']";
can we follow variable name convention camel Case?

2021-09-13 16:45 UTC, amrutha-sireesh commented on src/test/java/com/scale/stepdefs/SearchFrameworksPageSteps.java
> +        apibase.getRequest("search-api/frameworks");
can you please read the endpoint from from Config?

2021-09-14 08:43 UTC, ToyinOtak commented on src/main/java/com/scale/businessPages/AgreementPage.java
> +    private Logger log = Log.getLogger(ContactCCSPage.class);
great spot, this has now been updated. Looks like the existing code has the wrong name conventional which I have also updated

2021-09-16 09:01 UTC, merged